sudo: false
language: java
jdk:
  - openjdk8
cache:
  directories:
  - "$HOME/.cache"
  
jobs:
  include:
    - stage: test and report to Xray
      script: mvn clean compile test --file pom.xml
      script:
        - 'echo xt1: $XRAY_TOKEN'
        - 'curl -H "Content-Type: text/xml" -H "Authorization: Bearer $XRAY_TOKEN" --data @target/surefire-reports/TEST-com.xpand.java.CalcTest.xml  "https://xray.cloud.xpand-it.com/api/v2/import/execution/junit?projectKey=CALC"'
     
